### ISSUE TITLE
Missing predefined IO for raw JSON values

### ISSUE THREAD

**Issue by makkarpov** [Stiffstream/json_dto#10]
Somethimes there is a need to extract raw value from object tree, e.g. if value structure is irrelevant or variable. This can be accomplished by storing a field of type `rapidjson::Value`, which can hold any JSON value.

However, this does not compile:

```
#include <json_dto/pub.hpp>

struct Test {
    rapidjson::Value test;

    template <typename IO>
    void json_io(IO &io) {
        io & json_dto::mandatory("test", test);
    }
};

static void test() {
    Test t;
    json_dto::to_json(t);
}
```

failing with 

`error: ‘class rapidjson::GenericValue<rapidjson::UTF8<> >’ has no member named ‘json_io’`

It would be useful to have such predefined reader/writer.

**Comment by eao197** [comment]
Thanks for reporting.

I hope I can add support for that feature at the beginning of the next week.

**Comment by makkarpov** [comment]
Nevermind, `rapidjson::Document` can be serialized just fine.

Moreover, it is an only possible option, since `rapidjson::Value` depends on allocator and can cause segmentation faults if used alone (that is what I found after debugging `SIGSEGV`'s :))
