### ISSUE TITLE
Feature request: read-only fields

### ISSUE THREAD

**Issue by omartijn** [Stiffstream/json_dto#11]
I'm thinking it could be useful to have fields that are explicitly set to read-only, which will serialize _to_ json normally, but simply ignore the field when reading _from_ json.

Right now, we can of course make a field `optional_no_default`, which ensures we don't get an error when reading from json while not having the field, but this is not as explicit as marking it as read-only. Also, it might result in unwanted behaviour if the json _does_ contain the optional field. Additionally, a read-only field could accept a const-reference when seriailizing which would of course never work with an optional field (since it might need to write to the field).

I could whip up a PR if this is something we might want in json_dto.

**Comment by eao197** [comment]
Hi!

It's an interesting idea. However, the 10 and 11 of May are holidays in our country, so we can return to that issue after a couple of days.

**Comment by omartijn** [comment]
Well, I couldn't wait, so I decided to just cobble together something.

**Comment by eao197** [comment]
Hi!

There are two things I don't like about adding a support for 'readonly' fields to json-dto library as a new library feature.

The first is the opinion that the same effect can already be obtained by using custom Reader_Writer for a field. Something like:
```cpp
struct serializable_only {
  template< typename T >
  void read( T &, const rapidjson::Value & ) const noexcept { /* nothing to do */ }

  template< typename T >
  void write( const T & what, rapidjson::Value & to, rapidjson::MemoryPoolAllocator<> & allocator ) const
  {
    using json_dto::write_json_value;
    write_json_value( what, to, allocator ); 
  }
};
...
struct my_data {
  int v1_;
  int v2_;
  ...
  template< typename Json_Io >
  void json_io( Json_Io & io ) {
    io & json_dto::mandatory("v1", v1_)
        & json_dto::optional_no_default(serializable_only{}, "v2", v2_);
  }
};
```

The second is possible difficulties with understanding the term *read-only*. Some can think that *read-only* means a possibility to read a value from the object in the memory (e.g. field can only be serialized, but not deserialized), while someone else can think strictly opposite: the value can only be read from a textual JSON representation, but can't be written back (e.g. field can only be deserialized).

**Comment by eao197** [comment]
I think also that there is another possibility to implement such a feature with support only for *serializable-only* fields, but also for *deserializable-only* fields. It's a possibility to check the type of operation. Something like:
```cpp
struct my_data {
  int v1_;
  int v2_;
  int v3_;
  ...
  template< typename Json_Io >
  void json_io( Json_Io & io ) {
    // v1 has to be (de)serialized always.
    io & json_dto::mandatory("v1", v1_);
    // v2 has to be serialized only.
    if(serializing(io))
      io & json_dto::mandatory("v2", v2_);
    // v3 has to be deserialized only.
    if(deserializing(io))
      io & json_dto::optional("v3", v3_, 42);
  }
};
```
A new feature has to be added to json_dto in that case: new functions `serializing` and `deserializing`.

**Comment by omartijn** [comment]
I completely agree that there may be clearer terms out there than `readonly`. I mainly chose them to stick with the existing terminology of `read` and `write` for custom reader_writers. `serializeble_only` is probably clearer to a user.

I've looked at using a custom reader_writer for this, and this is in fact what I have done in my PR. You can't fully replicate the behaviour with _only_ a custom reader_writer, however. What the `json_dto::readonly` function adds is that it accepts a _const reference_, which isn't accepted by either `json_dto::mandatory` or `json_dto::optional`. This also adds support for using _unnamed temporaries_, e.g. things that are returned by a function.

The way I'm using this is that I write `non-intrusive json_io` functions for my classes. One thing they all have in common is that they all have a function that returns an ID by value. Since this can never be changed, it makes sense to have it _readonly_ (or _serializable_only_ if you will), but you can't directly do something like `json_dto::optional_no_default("id", value.ID())` because it expects a non-const lvalue.

**Comment by eao197** [comment]
I see that json-dto now has two drawbacks:

*1.* There is no support for const-objects to be serialized. Those objects can be in various forms:
```cpp
struct first_demo {
  const std::string protocol_version{ "1.0.0" };
  ...
  template< typename Json_Io >
  void json_io(Json_Io & io) {
    io & json_dto::mandatory("version", protocol_version)
      ...;
  }
};

struct second_demo {
  int Id() const { return 42; }

  template< typename Json_Io >
  void json_io(Json_Io & io) {
    io & json_dto::mandatory("id", Id())
      ...;
  }
};
```

*2.* There is no way to allow a field to be serializable-only or deserializable-only.

One approach to cope with those issues is your PR with new helper functions `readonly`.

I'm afraid that this approach is not flexible enough. The more flexible way (I think) can be with new predicates `serializing`/`deserializing` those can be used in `json_io` body:
```cpp
struct second_demo {
  int Id() const { return 42; }

  template< typename Json_Io >
  void json_io(Json_Io & io) {
    if(serializing(io)) {
      // Assume that issue with const-object is already resolved
      // in new implementation of `mandatory`.
      io & json_dto::mandatory("id", Id())
    }
    ...;
  }
};
```
But now I'm in doubt because your approach looks much more declarative.

What do you think about using the code like: `if(serializing(io)) { io & mandatory(...); }`?

**Comment by eao197** [comment]
I've added support for const- and rvalue references to a separate branch: https://github.com/Stiffstream/json_dto/tree/const-objects-support
I think that with new implementations of `mandatory`/`optional`/`optional_no_default`/etc you can implement `serializable_only` as your own helper functions outside of `json_dto` namespace. Somewhat like:
```cpp
template< typename Field_Type >
auto serializable_only(
  json_dto::string_ref_t field_name,
  Field_Type && field)
{
  return json_dto::mandatory(
    readonly_writter_t<json_dto::default_reader_writer_t>{},
    field_name,
    std::forward<Field_Type>(field));
}
```

**Comment by omartijn** [comment]
Ah, this looks like an interesting idea. It does not exactly work, however, as soon as you try to _deserialize_ json into a struct with a const member. For this to work, you'd have to use something like you mentioned before, like `if (json_dto::is_serializing(io))`so that it doesn't try to deserialize into a const field (and throw a compile error).

The `is_serializing` trait is easily written, something like `std::is_same<json_input_t, io>::value` should do the trick, but for it to work the way we want it you'd have to use it inside an `if constexpr`, otherwise the compiler will still try to compile the code even when the trait returns false. `if constexpr` requires c++17, so that would mean bumping the required version for json_dto. It also would still fail on the static_assert that's been added now - even though it's never called, it's still generated, but that could be solved with SFINAE instead of the static_assert.

**Comment by eao197** [comment]
The main problem with this feature for me is afraid of the introduction of ambiguous/confusing functionality.

Let's see the following cases:

The first one. We have to serialize only some data into JSON. In that case, we can have types with const members or attributes that represented as methods. For example:
```cpp
struct demo {
  const version m_version;
  id id() const noexcept { return { 1, 2, 3 }; }
  ...
  template<typename Json_Io>
  void json_io(Json_Io & io) {
    io & json_dto::mandatory("version", m_version)
      & json_dto::mandatory("id", id())
      & ...;
  }
};
```
That case is covered by new changes in const-objects-support branch.

The second one. We have to deserialize only some data from JSON. In that case, we can just only read those fields we need. There is no need to add new functionality to json-dto.

Except for the case when we want to check the scheme. For example, we know that there are "version" and "id" attributes that should have some specific format and we want to check the presence and the format (and maybe values) of those attributes. In that case we can do something like:
```cpp
struct demo {
  ...
  template<typename Json_Io>
  void json_io(Json_Io & io) {
    version dummy_version;
    id dummy_id;
    io & json_dto::mandatory("version", dummy_version)
      & json_dto::mandatory("id", dummy_id)
      & ...;
  }
};
```

The third case. We have to serialize and deserialize some data. In that case, some kind of `serialize_only` or `deserialize_only` can have some sense. But what is that sense?

For example, I write code like that:
```cpp
template<typename Json_Io>
void demo::json_io(Json_Io & io) {
  io & json_dto::serialize_only("id", id()) & ...;
}
```
It is obvious that "id" attribute will be serialized. But what happens with "id" on deserialization? Will it be completely ignored? If it is ignored does it mean that we can successfully deserialize a JSON without "id" or with "id" that contains an invalid value?

There are questions with `deserialize_only` too. If I write:
```cpp
template<typename Json_Io>
void demo::json_io(Json_Io & io) {
  io & json_dto::deserialize_only("version", m_version) & ...;
}
```
does it mean that "version" is a mandatory attribute? But what if it's optional?

Maybe it's possible to add new functions like `serialize_only` and `deserialize_only` to json-dto, but I'm afraid it will be hard to explain their meaning and use cases.

And it seems there could be different ways to achieve the same result...

**Comment by eao197** [comment]
One way is to use a temporary. Somewhat like:
```cpp
template<typename Json_Io>
void demo::json_io(Json_Io & io) {
  auto id = id();
  io & json_dto::mandatory("id", id) & ...;
}
```
The value of "id" will be stored on serialization and will be read/checked and then ignored on deserialization. `json_dto::optional`/`optional_no_default` can be used instead of `mandatory` and that will be pretty understandable.

It could be boring to writing code like:
```cpp
auto some_attr = GetSomeAttrValue();
auto another_attr = GetAnotherAttrValue();
...
```
but maybe there is a way of writing your own wrapper around json-dto's `binder_t`. I'll try to make a sketch later.

**Comment by omartijn** [comment]
The `const-objects-support` branch doesn't support the case where only _some_ objects are read-only, while others are not, because as soon as you try to deserialize, you will get a compile error due to the `static_assert`, that makes it less than ideal, IMNSHO.

I understand that when _deserializing_, using a function like _deserialize_only_ could be confusing, because then you cannot specify whether it's mandatory or not. That doesn't apply to _serialize_only_, since there is no case of the field "not being there" - this is C++ after all. You could have the case of `std::optional`, perhaps, but that's it.

Using temporaries is what I've been doing so far. It works, more or less, if you then use `optional_no_default`, because making it mandatory would cause deserialization to fail if the field is missing, even though it has no observable effect (it writes to a temporary which is then immediately discarded). The downside of that is that it's clumsy and it can still cause failures if the field appears in the JSON with a wrong type.

If we go down the route of wrapping the existing `binder_t`, we'll need to rewrite the static_assert to an SFINAE, so it doesn't fail compilation as long as it isn't actually used. Otherwise the compiler will still try to generate the function because it's part of the class,

**Comment by eao197** [comment]
The `const-objects-support` branch is just an experimental step in an unknown direction. Don't regard it as a solution.

Your case tells me that there could be situations where a user has to read one set of fields and read another set. For example, someone can read obsolete attributes that should be taken into account but shouldn't be written back. In that case, `deserialize_only` can be very useful. And `deserialize_only` can be combined with `mandatory` and `optional`.

So I want to extend json-dto by some way of solving cases like yours. But don't know yet how to do it simple, understandable, flexible, and extendable. But it seems that your approach solves only a particular case. Because of that, I don't merge your PR into json-dto yet.

**Comment by eao197** [comment]
I implemented an updated version of `binder_t` with several new customization points. The code is in `binder-decomposition` branch. Such customization points allows to write code like that: https://github.com/Stiffstream/json_dto/blob/281ea2c955b9dae239269b177997d9fa976f6701/dev/sample/tutorial20.1/main.cpp#L107-L124

or like that:

https://github.com/Stiffstream/json_dto/blob/281ea2c955b9dae239269b177997d9fa976f6701/dev/sample/tutorial20.2/main.cpp#L111-L128

Implementation of `serialize_only` and related stuff can be found here: https://github.com/Stiffstream/json_dto/blob/281ea2c955b9dae239269b177997d9fa976f6701/dev/sample/tutorial20.1/main.cpp#L12-L105
Implementation of `deserialize_only` and related stuff can be found here: https://github.com/Stiffstream/json_dto/blob/281ea2c955b9dae239269b177997d9fa976f6701/dev/sample/tutorial20.2/main.cpp#L12-L109

I don't think that stuff like `serialize_only`/`deserialize_only` should be a part of json-dto library. But such new customization points allow anyone to write their own versions of `(de)serialize_only` of various complexity.

The new customization points are not documented yet. I plan to document them when I decided to include that functionality in the master branch.

**Comment by eao197** [comment]
I have extended a new example to show how `serialize_only` can be used with default `json_dto::optional` behavior: https://github.com/Stiffstream/json_dto/blob/44df77fad5521485e068effdf3fd69f048c175cd/dev/sample/tutorial20.1/main.cpp#L107-L134
Attributes "priority" and "version" will be serialized only if they have non-default values.

**Comment by omartijn** [comment]
That looks pretty clean, I must say.

**Comment by eao197** [comment]
The new functionality is now avaliable in v.0.2.12.
