### ISSUE TITLE
variant type

### ISSUE THREAD

**Issue by navono** [Stiffstream/json_dto#14]
Hi.

I have a dynamic type field in json, I simply declare it with `std::any` type, but it cannot be compiled.
Is this possible or not?

**Comment by eao197** [comment]
Hi!

json_dto is C++14 library and the only C++17 (or newer) type supported is `std::optional`. It means that json_dto doesn't support `std::variant` nor `std::any`.

At the moment we have no plans to upgrade json_dto to C++17. But you can add support for `std::any` by using any method of defining user IO for json_dto: [see here for examples](https://github.com/Stiffstream/json_dto#user-defined-io).

**Comment by navono** [comment]
Thank you for response. I'll check that.
